[package]
name = "typechex"
version = "0.1.0"
authors = ["Gabe Durazo <gabed@durazo.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
